CREATE TABLE IF NOT EXISTS genre (
                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS rating (
                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS film (
                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR NOT NULL,
                                description VARCHAR(200),
                                release_date DATE,
                                duration BIGINT,
                                rating_id INTEGER REFERENCES rating (id)
);

CREATE TABLE IF NOT EXISTS film_genre (
                                film_id INTEGER REFERENCES film (id) ON DELETE CASCADE,
                                genre_id INTEGER REFERENCES genre (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS person (
                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                email VARCHAR NOT NULL,
                                login VARCHAR NOT NULL,
                                name VARCHAR NOT NULL,
                                birthday DATE
);

CREATE TABLE IF NOT EXISTS film_like (
                                film_id INTEGER REFERENCES film (id) ON DELETE CASCADE,
                                liked_person_id INTEGER REFERENCES person (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friendship (
                                person_id INTEGER REFERENCES person (id) ON DELETE CASCADE,
                                friend_id INTEGER REFERENCES person (id) ON DELETE CASCADE,
                                is_confirmed BOOLEAN
);